require:
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  IgnoreCopDirectives: true
  Max: 120

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*.rb'
    - 'config/routes.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Naming/MethodParameterName:
  MinNameLength: 2

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'